package com.percyvega.cxf.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-01-10T04:01:05.057-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://cxf.percyvega.com/service/Orders", name = "Orders")
@XmlSeeAlso({com.percyvega.cxf.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://cxf.percyvega.com/service/Orders/ProcessOrderPlacement")
    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://cxf.percyvega.com/schema/Order", partName = "orderInquiryResponse")
    public com.percyvega.cxf.schema.order.OrderInquiryResponseType processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://cxf.percyvega.com/schema/Order")
        com.percyvega.cxf.schema.order.OrderInquiryType orderInquiry
    );
}
